apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepubsub-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlepubsub-spring
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: googlepubsub-spring
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: googlepubsub-spring
        image: arawa3/googlepubsub-spring
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
        - containerPort: 80